### ISSUE TITLE
Feature request: show tab completion options above input

### ISSUE THREAD

**Issue by khughitt** [x-motemen/gore#191]
Greetings!

I'm not sure how feasible this would be, but it would be pretty useful to display a (subset) of all of the auto-completion options in something like a popup/modal dialog above in the input prompt, along the lines of how completion behaves in IPython, ZSH, fzf, etc.

This way, the user can see all (or many) of the possible options, making it easier to find one they are looking for, even if they don't remember the exact name.

Thanks for your work on this great project!

Cheers.

**Comment by itchyny** [comment]
Unlikely to support this feature, so closing. But if you implemented this, pull request is welcome.
