### ISSUE TITLE
Println or Printf repeating with old values

### ISSUE THREAD

**Issue by rsrini7** [x-motemen/gore#210]
> gore -version                                                                            ─╯
gore 0.5.3 (rev: HEAD/go1.16.7)

gore> :clear
gore> :import fmt math
gore> fmt.Printf("%f",math.Sqrt(7))
2.6457518
nil
gore> fmt.Printf("%f",math.Sqrt(7))
2.6457512.6457518
nil
gore> fmt.Printf("%f",math.Sqrt(7))
2.6457512.6457512.6457518
nil
gore> fmt.Printf("%f",math.Sqrt(7))
2.6457512.6457512.6457512.6457518
nil
gore> fmt.Println(math.Sqrt(7))
2.6457512.6457512.6457512.6457512.6457513110645907
19
nil
gore> fmt.Println(math.Sqrt(7))
2.6457512.6457512.6457512.6457512.6457513110645907
2.6457513110645907
19
nil
gore> fmt.Println(7)
2.6457512.6457512.6457512.6457512.6457513110645907
2.6457513110645907
2.6457513110645907
7
2
nil
gore> fmt.Println(7)
2.6457512.6457512.6457512.6457512.6457513110645907
2.6457513110645907
2.6457513110645907
7
7
2
nil

**Comment by itchyny** [comment]
See https://github.com/x-motemen/gore#faqcaveats, https://github.com/x-motemen/gore/issues/67#issuecomment-576221444.

**Comment by xyproto** [comment]
Similar behavior here:

```go
❯ gore
gore version 0.6.0  :help for help
gore> :import fmt
gore> x := make(map[string]string)
map[string]string{}
gore> x["hi"] = "hello"
"hello"
gore> for k, v := range x { fmt.Printf("asdf\n") }
asdf
gore> for k, v := range x { fmt.Printf("asdf\n") }
asdf
asdf
gore> for k, v := range x { fmt.Printf("asdf\n") }
asdf
asdf
asdf
gore> for k, v := range x { fmt.Printf("asdf\n") }
asdf
asdf
asdf
asdf

❯ git reflog
2f8f9c6 (HEAD -> main, tag: v0.6.0, origin/main, origin/HEAD) HEAD@{0}: clone: from https://github.com/x-motemen/gore.git
```
