### ISSUE TITLE
please support offline

### ISSUE THREAD

**Issue by tigerinus** [x-motemen/gore#219]
Had an internet outage today, then found that `gore` does not give a prompt.

Understood that there is difficulty supporting offline/cached packages (https://github.com/x-motemen/gore/pull/165), but is it possible to at least show the prompt and allow built-in and some basic packages?

My scenario is that I just need a REPL to try out some Go syntax which doesn't really need much packages besides `fmt`.

**Comment by itchyny** [comment]
I tested right now, and `gore 0.5.5` works offline in my environment.

**Comment by tigerinus** [comment]
interesting... it doesn't repro again.

I simply pulled my cable - not sure if it's the same situation as internet outage (router works but ISP doesn't)

Does `gore` access network for anything during its startup?

**Comment by itchyny** [comment]
When `gore` cannot find the pretty printer package `github.com/k0kubun/pp/v3` in local filesystem module cache (`$(go env GOPATH)/pkg/mod`), it checks connectivity to `GOPROXY` (default `proxy.golang.org`) with 5s timeout. If it fails, it uses the standard `fmt` package.
