### ISSUE TITLE
linux go build failed

### ISSUE THREAD

**Issue by QGB** [x-motemen/gore#222]
```
# go build
/go/pkg/mod/github.com/mattn/go-runewidth@v0.0.14/runewidth.go:7:2: //go:build comment without // +build comment

```

**Comment by itchyny** [comment]
I think you are using Go 1.16 which is already unsupported per [Release Policy](https://go.dev/doc/devel/release#policy). Please use supported version of Go.

**Comment by QGB** [comment]
gore: could not load 'fmt' package: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr:

**Comment by itchyny** [comment]
That error message says what's wrong.
